apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: "lemursync"
  app.kubernetes.io/part-of: "ambra"
  app.kubernetes.io/component: "backend"
namespace: default
resources:
  - job.yaml
