BUCKETS: mogilefs-prod-repo:plos-corpus-prod,plive:plos-published-prod
COLLECTION_NAME: corpus-migration
MOGILE_DATABASE_URL: 
MOGILE_TRACKERS: mogile-101.soma.plos.org:7001,mogile-102.soma.plos.org:7001,mogile-103.soma.plos.org:7001
TOPIC_ID: corpus-migration
