
SET FILES LOG SIZE 1  -- trigger a checkpoint when the log file reaches 1MB
SET FILES DEFRAG 1   -- when the above trigger is fired, defrag the DB if it has grown by 1%

CREATE CACHED TABLE IF NOT EXISTS buckets (
  bucketId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
  bucketName VARCHAR(1000) NOT NULL UNIQUE
);

CREATE CACHED TABLE IF NOT EXISTS objects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
  bucketId INTEGER REFERENCES buckets NOT NULL,
  key VARCHAR (1000) NOT NULL,
  checksum VARCHAR (1000) NOT NULL,
  timestamp timestamp NOT NULL,
  urls VARCHAR (3000), -- direct http paths to object, space separated
  downloadName VARCHAR (1000),  -- the name of the file when downloaded
  contentType VARCHAR (200), -- the mime type
  size INTEGER NOT NULL,  -- the file size in bytes
  tag VARCHAR (200),
  status TINYINT DEFAULT 0 NOT NULL, -- 0: used, 1: deleted
  versionNumber INTEGER NOT NULL
);

DROP INDEX keysum IF EXISTS;
CREATE UNIQUE INDEX keysum ON objects(bucketId, key, versionNumber);

DROP INDEX objkey IF EXISTS;
CREATE INDEX objKey ON objects(bucketId, key);
