
--DROP TABLE IF EXISTS assets;
--DROP TABLE IF EXISTS buckets;
--DROP INDEX IF EXISTS keysum;

CREATE TABLE IF NOT EXISTS buckets (
  bucketId INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
  bucketName VARCHAR(1000) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
  bucketId INTEGER REFERENCES buckets NOT NULL,
  key VARCHAR (1000) NOT NULL,
  checksum VARCHAR (1000) NOT NULL,
  timestamp timestamp NOT NULL,
  url VARCHAR (1000), -- servable path to asset
  downloadName VARCHAR (1000),  -- the name of the file when downloaded
  contentType VARCHAR (200), -- the mime type
  size INTEGER NOT NULL,  -- the file size in bytes
  tag VARCHAR (200)
);

--DROP INDEX keysum IF EXISTS;
--CREATE UNIQUE INDEX keysum ON assets(bucketId, key, checksum, size);
