reposvc:
  build: reposvc
  volumes:
    - ../target:/build
  links:
    - repodb:repodb
    - tracker:tracker
  ports:
    - "8088:8080"

repodb:
  build: repodb.mysql
  volumes:
    - ../src/main/resources:/mysql_schema

tracker:
  build: tracker
#  image: rail44/mogile-tracker
   ports:
    - "7008:7001"
  links:
    - db
    - node

node:
  image: rail44/mogile-node

db: # database for mogile
  image: orchardup/mysql
