#!/usr/bin/env bash

#set -x
set -o errexit

. /usr/share/debconf/confmodule

TOMCAT7_USER=repo
TOMCAT7_GROUP=repo
HOME=[[contentrepo.debInstallDir]]

function process_env_template {
	CONTEXT_TEMPLATE=$1

  ls -lh $CONTEXT_TEMPLATE

	echo "Processing template $CONTEXT_TEMPLATE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPLATE)
EOF
" > $CONTEXT_TEMPLATE
}

case "$1" in
    configure)

  # create user/group

	if ! getent group "$TOMCAT7_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$TOMCAT7_GROUP" --quiet
	fi
	if ! id $TOMCAT7_USER > /dev/null 2>&1 ; then
	    adduser --system --home $HOME --no-create-home \
		--ingroup "$TOMCAT7_GROUP" --disabled-password --shell /bin/false \
		"$TOMCAT7_USER"
	fi

  chmod +x $HOME/bin/*.sh
  chown -Rh $TOMCAT7_USER:$TOMCAT7_GROUP $HOME

  GET="db_get [[artifactId]]"


########### BEGIN app-specific code ###########

  # Fetching configuration from debconf

  $GET/contentrepo_db_host && export CONTENTREPO_DB_HOST=$RET
  $GET/contentrepo_db_password && export CONTENTREPO_DB_PASSWORD=$RET
  $GET/contentrepo_port && export CONTENTREPO_PORT=$RET
  $GET/control_port && export CONTROL_PORT=$RET
  $GET/crepo_storage_location && export CREPO_STORAGE_LOCATION=$RET
  $GET/contentrepo_mogile_trackers && export CONTENTREPO_MOGILE_TRACKERS=$RET

########### END app-specific code ###########


  # removes the saved values, so they need to be re-entered the next time around
  # db_purge

  # generate configs from templates
  process_env_template $HOME/conf/context-mogile.xml
  cat $HOME/conf/context-mogile.xml
  
  process_env_template $HOME/conf/context-local.xml
  cat $HOME/conf/context-local.xml
  
  process_env_template $HOME/conf/context.xml
  cat $HOME/conf/context.xml

  process_env_template $HOME/conf/server.xml
  cat $HOME/conf/server.xml

esac

