#!/usr/bin/env bash
#set -x
set -o errexit

. /usr/share/debconf/confmodule

NAME=contentrepo

TOMCAT7_USER=repo
TOMCAT7_GROUP=repo
HOME=/opt/plos/$NAME

function process_env_template {
	CONTEXT_TEMPLATE=$1
	OUTFILE=$2

  ls -lh $CONTEXT_TEMPLATE

	echo "Processing template $CONTEXT_TEMPLATE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPLATE)
EOF
" > $OUTFILE
}

case "$1" in
  configure|reconfigure)

  # create user/group

	if ! getent group "$TOMCAT7_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$TOMCAT7_GROUP" --quiet
	fi
	if ! id $TOMCAT7_USER > /dev/null 2>&1 ; then
	    adduser --system --home $HOME --no-create-home \
		--ingroup "$TOMCAT7_GROUP" --disabled-password --shell /bin/false \
		"$TOMCAT7_USER"
	fi

	chmod +x $HOME/bin/*.sh
	chown -Rh $TOMCAT7_USER:$TOMCAT7_GROUP $HOME

	echo "Fetching configuration from debconf"
	GET="db_get [[artifactId]]"

########### BEGIN app-specific code ###########

  # Fetching configuration from debconf

  $GET/contentrepo_db_host && export CONTENTREPO_DB_HOST=$RET
  $GET/contentrepo_db_password && export CONTENTREPO_DB_PASSWORD=$RET
  $GET/contentrepo_port && export CONTENTREPO_PORT=$RET
  $GET/control_port && export CONTROL_PORT=$RET
  $GET/crepo_storage_location && export CREPO_STORAGE_LOCATION=$RET
  $GET/contentrepo_mogile_trackers && export CONTENTREPO_MOGILE_TRACKERS=$RET

########### END app-specific code ###########

	process_env_template $HOME/conf/context-$CREPO_STORAGE_LOCATION.template.xml $HOME/conf/context.xml

	process_env_template $HOME/conf/server.template.xml $HOME/conf/server.xml

  process_env_template $HOME/conf/tomcat-users.template.xml $HOME/conf/tomcat-users.xml

	process_env_template $HOME/bin/setenv.template.sh $HOME/bin/setenv.sh
  
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

service [[artifactId]] stop || true
